name: Python package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-dink
    name: python test and build
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2

    - uses: attacking-lab/actions/.github/actions/github-credentials-store@main
      with:
        password: ${{ secrets.CI_PAT }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup environment
      run: |
        sudo apt update -y && sudo apt install make
        python -m pip install uv==0.8.5
        echo "UV_FLAGS=--exact --isolated --frozen" >> $GITHUB_ENV

    - name: Check formatting
      run: |
        make --trace format

    - name: Check linting
      run: |
        make --trace lint

    - name: Check typing
      run: |
        make --trace mypy

    - name: Run tests
      run: |
        mongo_cid=$(docker run -d -p 27017:27017 mongo)
        TEST_FLAGS=--with_mongodb make --trace test
        docker kill $mongo_cid

    - name: Test build
      run: |
        make --trace build
        pip install dist/enochecker3-*.tar.gz
